Feature/course work 4
Dimon4ik812/course_work_4 pull request #1
Opened 2024-11-07 10:40 UTC by Dimon4ik812

2024-11-07 17:18 UTC, painassasin requested changes

2024-11-07 17:18 UTC, painassasin commented on config/settings.py
> +EMAIL_HOST_USER = 'Poxxyuct812@yandex.ru'
Эту переменную также нужно задавать через .env, чтобы кто угодно мог взять твой код, запустить и отправлять рассылки от своего пользователя

2024-11-07 17:18 UTC, painassasin commented on config/settings.py
> +            'LOCATION': 'redis://127.0.0.1:6379/1',
Ссылку нужно вынести в .env, как с базой  - назвать можно CACHE_URL или REDIS_URL

2024-11-07 17:18 UTC, painassasin commented on newapp/forms.py
> +        if name.lower() and description.lower() in [
Требований в ТЗ не было на валидацию этих полей

2024-11-07 17:18 UTC, painassasin commented on newapp/models.py
> +class StyleFormMixin:
Этот код относится к формам, поэтому нужно размещать в forms.py

2024-11-07 17:18 UTC, painassasin commented on newapp/models.py
> +    success = models.BooleanField(default=False)
Для чего это поле?

2024-11-07 17:18 UTC, painassasin commented on newapp/models.py
> +    Mail_server_response = models.TextField(blank=True)  # Разрешаем пустое значение
Поля должны быть в нижнем регистре (дата отправки тоже) - это требование pep8

2024-11-07 17:18 UTC, painassasin commented on newapp/models.py
> +    recipients = models.ManyToManyField(MailingRecipient, blank=True)
Попытку нужно связать только с рассылкой. Уже через рассылку ты сможешь получить и клиентов и сообщение

2024-11-07 17:18 UTC, painassasin commented on newapp/utils/logger.py
> +    logging.basicConfig(
@Логирование настраивается в settings.py, в переменной LOGGING,  например:

https://stackoverflow.com/questions/45707830/how-to-log-a-file-in-django

https://episyche.com/blog/logging-with-django

И где нужно логирование потом просто создавай логер и логируй
```python
logger = logging.getLoger(__name__)

logger.info('Some text')

2024-11-07 17:18 UTC, painassasin commented on newapp/views.py
> +                    "Poxxyuct812@yandex.ru",  # Замените на Ваш email
Возьми его из settings.py через импорт, а там укажи через .env

2024-11-07 17:18 UTC, painassasin commented on users/forms.py
> +                in ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция", "радар"]
Кажется этого не было в ТЗ?)

2024-11-07 17:18 UTC, painassasin commented on users/management/commands/createadmin.py
> +        user = User.objects.create(email="test@mail.ru", first_name="admin", last_name="admin")
Для таких целей правильнее заводить переменные в settings.py через .env, например ADMIN_EMAIL, ADMIN_PASSWORD и использовать их

Чтобы я при запуске кода мог поставить свои значения не внося правки в код

2024-11-07 17:18 UTC, painassasin commented on users/views.py
> +            new_password = "".join(
Выглядит как отдельная функция
```python
def generate_random_password(length: int = 8) -> str:
    return new_password = "".join(
        secrets.choice(string.ascii_letters + string.digits + string.punctuation)
        for i in range(length)
    )

2024-11-07 17:27 UTC, Dimon4ik812 commented on config/settings.py
> +EMAIL_HOST_USER = 'Poxxyuct812@yandex.ru'
исправил

2024-11-07 17:32 UTC, Dimon4ik812 commented on config/settings.py
> +            'LOCATION': 'redis://127.0.0.1:6379/1',
исправил

2024-11-07 17:33 UTC, Dimon4ik812 commented on newapp/forms.py
> +        if name.lower() and description.lower() in [
исправил

2024-11-07 17:35 UTC, Dimon4ik812 commented on newapp/models.py
> +class StyleFormMixin:
исправил

2024-11-07 17:37 UTC, Dimon4ik812 commented on newapp/models.py
> +    success = models.BooleanField(default=False)
какое именно ?
1. Получатель
2. владелец
3. заблокировано или разблокировано 
4. статус отправки если не успешно False, если успешно True

2024-11-07 17:41 UTC, Dimon4ik812 commented on newapp/views.py
> +                    "Poxxyuct812@yandex.ru",  # Замените на Ваш email
исправил

2024-11-07 17:42 UTC, Dimon4ik812 commented on users/forms.py
> +                in ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция", "радар"]
исправил

2024-11-07 17:46 UTC, Dimon4ik812 commented on users/management/commands/createadmin.py
> +        user = User.objects.create(email="test@mail.ru", first_name="admin", last_name="admin")
исправил

2024-11-07 18:14 UTC, Dimon4ik812 commented on users/views.py
> +            new_password = "".join(
исправил

2024-11-07 18:43 UTC, Dimon4ik812 commented on newapp/utils/logger.py
> +    logging.basicConfig(
исправил

2024-11-08 08:29 UTC, painassasin commented on newapp/models.py
> +    success = models.BooleanField(default=False)
Статус отправки - это поле для рассылки не нужно. Все статусы рассылки ты хранишь в модели `MailingAttempt`

2024-11-08 11:08 UTC, Dimon4ik812 commented on newapp/models.py
> +    success = models.BooleanField(default=False)
исправил

2024-11-08 11:17 UTC, Dimon4ik812 commented on newapp/models.py
> +    Mail_server_response = models.TextField(blank=True)  # Разрешаем пустое значение
исправил

2024-11-08 11:39 UTC, painassasin approved these changes

2025-04-21 11:28 UTC, merged